### ISSUE TITLE
I want to know how to use it

### ISSUE THREAD

**Issue by Gogo-GITHUB** [BinRad/Minimal-Text-Editor#2]
![20200525090241](https://user-images.githubusercontent.com/55140866/82769352-b2182100-9e66-11ea-9256-961c4d338298.png)

I want to know how to use it and how to save them.
thank you！

**Comment by BinRad** [comment]
![image](https://user-images.githubusercontent.com/50124594/82773284-a4837c80-9e0f-11ea-961f-db5dffd930ee.png)
![image](https://user-images.githubusercontent.com/50124594/82773301-acdbb780-9e0f-11ea-886e-13b900c5a283.png)
This is the code running (above). You can compile and run the code by doing the following:
tasm TEXT
tlink TEXT/t
TEXT read.txt

**Comment by BinRad** [comment]
Please let me know if that helps!

**Comment by Gogo-GITHUB** [comment]
![20200525090241](https://user-images.githubusercontent.com/55140866/82795665-e3184600-9ea6-11ea-8d81-e0a736794edf.png)
When I enter the editing interface, garbled characters appear. Can you show the interface where the program runs normally

**Comment by BinRad** [comment]
Here are the steps to run and use the code I have posted: 
1. Is to mount your c drive that contains the .asm file, batch file, and sample text file that I posted
![image](https://user-images.githubusercontent.com/50124594/82822702-34f3a880-9e74-11ea-9226-dcbe61806771.png)
2. Run the batch file (by typing in 'r' and pressing enter) I uploaded last night in order to assemble and run the code, loading in the sample code I also uploaded last night
![image](https://user-images.githubusercontent.com/50124594/82822813-68cece00-9e74-11ea-9efd-c447f877d625.png)
3. You should now see the title screen below
![image](https://user-images.githubusercontent.com/50124594/82822864-7be19e00-9e74-11ea-8370-94a67934e586.png)
4. By pressing any key the sample text file I included should be opened and should look as follows:
![image](https://user-images.githubusercontent.com/50124594/82822985-b9462b80-9e74-11ea-8160-8b165e657d31.png)
5. Write what you want and then save the file by pressing [ctrl]+[s]
![image](https://user-images.githubusercontent.com/50124594/82823062-dd097180-9e74-11ea-912e-c42cb9a7940d.png)

Please feel free to ask any more questions if anything at all is unclear. 

Note: using the application to create a new text file will result in jumbled characters as can be seen below:
![image](https://user-images.githubusercontent.com/50124594/82823318-586b2300-9e75-11ea-9530-f94b253477a1.png)
This was a limited school project that I really enjoyed, however once the project was due I moved on to the next project I was working on (which is why it is not completely polished). This project was really proof of concept, I could add more functionality, such as new file creation, but that was not one of the requirements of the assignment unfortunately.

**Comment by Gogo-GITHUB** [comment]
1.When i type“TEXT READ.TXT",It can enter such an interface.

![_20200526094200](https://user-images.githubusercontent.com/55140866/82852385-6aac9600-9f35-11ea-88d0-1bba1dfec953.png)
2.When I entered the editing interface, it appeared garbled characters, and pressing exit will be stuck and unable to exit.
![_20200525164235](https://user-images.githubusercontent.com/55140866/82852675-21a91180-9f36-11ea-8021-e70c4d79440d.png)
![_20200526094146](https://user-images.githubusercontent.com/55140866/82852683-24a40200-9f36-11ea-99df-1b65c336485f.png)
3.I think some errors like ”mov al，？“ happened because of a warning when I masm TEXT.ASM.
![_20200526094153](https://user-images.githubusercontent.com/55140866/82852827-8a908980-9f36-11ea-917f-1521d2c10d8a.png)

**Comment by Gogo-GITHUB** [comment]
Hi, I'm using Vmware and MASM to run your code.This may also be the cause of the error. But i don't know how to solve.

**Comment by BinRad** [comment]
Yes that seems to be the issue. The assembler I use is called TASM and was made by Borland. It also seems that somehow when you are using MASM, at least just from looking at the picture above, the resolution your dos window is using is not the native 80x25 character default for text mode as specified by int 10h.

**Comment by BinRad** [comment]
I would recommend using dosbox and TASM if it's available to you. I'll look around for MASM so I can recreate your issue and try to fix it. It seems like your really have two separate issues from what I can see:
1. The resolution that VMWare is giving you is not the normal dos resolution which is why the title screen looks skewed the way that it does. 
2. (this is my assumption) The ? in the mov instructions are probably messing with MASM and not letting the program be assembled correctly, which is hwy there are warnings with MASM. 

For the first issue just set vmware to a different resolution. For the second issue I'll change the '?' to ' ' and re upload it and we can see if it works.

**Comment by Gogo-GITHUB** [comment]
The problem I showed above is that it has changed the '?' to ' '.

**Comment by Gogo-GITHUB** [comment]
1.When i use in dosbox，The interface is like this。
![_20200527223403](https://user-images.githubusercontent.com/55140866/83034111-764da900-a06a-11ea-84be-64b2e567d71e.png)
2.When I enter the editing interface, it cannot display the menu and cannot exit.But it can save changes.
![_20200527223511](https://user-images.githubusercontent.com/55140866/83034425-d2183200-a06a-11ea-98f5-f36bb281d4b6.png)

**Comment by Gogo-GITHUB** [comment]
I think the second issue is the key issue.It may be caused by some small changes.

**Comment by BinRad** [comment]
Would you be willing to try TASM?

**Comment by BinRad** [comment]
I just reuploaded it from my computer just to make sure we were using the same thing, which it appears we are. Would you be willing to try TASM?

**Comment by BinRad** [comment]
I uploaded the assembled DOS application. You can find it with the .COM extension in the list of files. I hope this helps.

**Comment by Gogo-GITHUB** [comment]
I am very willing to try TASM.Thank you very much for your help.

**Comment by BinRad** [comment]
Of course. Thank you so much for looking at my code and trying my application, I really appreciate the feedback!

**Comment by Gogo-GITHUB** [comment]
I can't find a way to learn tasm download. Would you send me your tasm？

**Comment by Gogo-GITHUB** [comment]
![_20200528094423](https://user-images.githubusercontent.com/55140866/83264879-585f8000-a1f3-11ea-97d0-f229523c9af8.
![_20200528094434](https://user-images.githubusercontent.com/55140866/83264978-73ca8b00-a1f3-11ea-9eeb-631465b0f532.png)
I can run yours normally assembled DOS application. But I am missing the tool to generate normally assembled DOS application.

**Comment by BinRad** [comment]
I'm happy the application runs on your computer. Unfortunately, I am unsure if I am allowed to distribute the copy of TASM that I have.
